version: "3"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - elasticsearch
  elasticsearch:
      image: elasticsearch:7.8.1
      environment:
        - discovery.type=single-node
      ports:
        - "9200:9200"
