# Generated by Django 3.2.13 on 2022-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearBitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('streetAddress', models.CharField(max_length=255)),
                ('foundedYear', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
            ],
        ),
    ]
