# Generated by Django 3.2.13 on 2022-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clearbitdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbitdata',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
